vouch:
  # logLevel: debug
  # testing: true
  listen: 0.0.0.0
  port: 9090
  allowAllUsers: true

  jwt:
    issuer: Vouch
    compress: false

  cookie:
    name: my-vouch-ct
    secure: false
    # domain: localhost # VOUCH_COOKIE_DOMAIN

  headers:
    jwt: X-Vouch-Token
    querystring: access_token
    redirect: X-Vouch-Requested-URI
    accesstoken: X-Vouch-IdP-AccessToken
    idtoken: X-Vouch-IdP-IdToken

  # post_logout_redirect_uris: # VOUCH_POST_LOGOUT_REDIRECT_URIS
  #   - https://<SECRET>.uk.auth0.com/v2/logout?client_id=<SECRET>&returnTo=https://localhost/

oauth:
  # Generic OpenID Connect
  # including okta
  provider: oidc
  scopes:
    - openid
    - email
    - profile
  # callback_url: https://localhost/sso/auth # OAUTH_CALLBACK_URL
